backend:
  name: git-gateway
  branch: main

media_folder: "src/content/posts/images" # Where uploaded files are stored (relative to repo root)
public_folder: "/src/content/posts/images" # How those files are accessed in the browser

media_library:
  name: uploadcare # Or leave this out for the default

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "src/content/posts"
    extension: "mdx"
    format: "frontmatter"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "Featured Image"
        name: "image"
        widget: "object"
        required: false
        fields:
          - { label: "Image", name: "src", widget: "image", required: false }
          - {
              label: "Alt Text",
              name: "alt",
              widget: "string",
              required: false,
              default: "A description of the image",
            }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
